defaults: &defaults
  working_directory: /app
  docker:
    - image: docker:17.05.0-ce-git
      environment:
        VERSION: "$VERSION"
  steps:
      - checkout
      - run:
          name: Setting Cache Key
          command: echo "$VERSION" > .VERSION
      - run:
          name: Preparing Dockerfile
          command: |
            cp Dockerfile.template Dockerfile
            sed -i -e 's/<version>/'"$VERSION"'/g' Dockerfile
      - setup_remote_docker
      - restore_cache:
          keys:
            - cache-{{ checksum ".VERSION" }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build Docker Image
          command: |
            docker build --pull -t app --cache-from=app --build-arg COPY_FILES="" .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: cache-{{ checksum ".VERSION" }}
          paths:
            - /caches/app.tar
      - deploy:
          name: Push application Image
          command: |
            docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
            docker tag app sctr/docker-symfony:$VERSION
            if [[ "$LATEST" = "true" ]]; then docker tag app sctr/docker-symfony:${CIRCLE_SHA1}; fi
            if [[ "$LATEST" = "true" ]]; then docker tag app sctr/docker-symfony:latest; fi
            docker push sctr/docker-symfony

version: 2
jobs:
  v7.0:
    <<: *defaults
    environment:
      VERSION: "7.0"
  v7.1:
    <<: *defaults
    environment:
      VERSION: "7.1"
  v7.2:
    <<: *defaults
    environment:
      VERSION: "7.2"
      LATEST: "true"

workflows:
  version: 2
  build:
    jobs:
      - v7.0:
          context: org-global
      - v7.1:
          context: org-global
      - v7.2:
          context: org-global
