defaults: &defaults
  working_directory: /app
  docker:
    - image: docker:17.05.0-ce-git
      environment:
        VERSION: "$VERSION"
  steps:
      - checkout
      - run:
          name: Preparing Dockerfile
          command: |
            cp Dockerfile.template Dockerfile
            sed -i -e 's/<version>/'"$VERSION"'/g' Dockerfile
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build Docker Image
          command: docker build --pull -t sctr/docker-symfony:$VERSION --cache-from=app-$VERSION .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app-$VERSION.tar app-$VERSION
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app-$VERSION.tar
      - deploy:
          name: Push application Image
          command: |
            docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
            docker tag sctr/docker-symfony:${CIRCLE_SHA1}
            docker push sctr/docker-symfony:$VERSION

version: 2
jobs:
  v7.0:
    <<: *defaults
    environment:
      VERSION: "7.0"
  v7.1:
    <<: *defaults
    environment:
      VERSION: "7.1"
  v7.2:
    <<: *defaults
    environment:
      VERSION: "7.2"

workflows:
  version: 2
  build:
    jobs:
      - v7.0
      - v7.1
      - v7.2
