name: Build Docker Image

on:
    push:

env:
    REGISTRY: ghcr.io
    REGISTRY_IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
    build-and-push:
        strategy:
            fail-fast: false
            matrix:
                phpversion:
                    - 8.3
                    - 8.4
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push ${{ matrix.phpversion }}
              uses: docker/build-push-action@v6
              with:
                  context: .
                  tags: ${{ env.REGISTRY_IMAGE_NAME }}:${{ matrix.phpversion }}
                  file: ./${{ matrix.phpversion }}/Dockerfile
                  platforms: linux/amd64,linux/arm64
                  cache-from: type=gha
                  cache-to: type=gha,mode=max